version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: habit-tracker-api
    environment:
      MONGO_URI: mongodb://mongo:27017/appdb
      APP_HOST: 0.0.0.0
      APP_PORT: "8000"
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    command: ["--wiredTigerCacheSizeGB", "1"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/appdb", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
